# RMDIR Non-Empty Directory Test
#
# Tests that RMDIR (non-recursive) properly fails when trying to remove
# a directory that contains files.

target: "file:///tmp/sai3bench-rmdir-nonempty/"
duration: 3s
concurrency: 4

prepare:
  # Pre-create some directories with files in them
  ensure_objects:
    - base_uri: "file:///tmp/sai3bench-rmdir-nonempty/filled-dirs/"
      count: 20
      size_distribution: 4096
  cleanup: true

workload:
  # Try to remove the directory without recursive flag
  # This SHOULD fail because it contains files
  - op: rmdir
    path: "filled-dirs/"
    recursive: false
    weight: 100
